include:
    - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v1.0.5
      inputs:
          vm-hostname: media.vm.xbhl.intranet
          vm-ssh-username: $SSH_USER
          vm-ssh-private-key: $SSH_PRIVATE_KEY
          service-name: traefik:media-vm
          container-name: traefik
          container-location: /opt/containers/traefik
          cloudflare-dns-entry-name: traefik-media.intranet.xbhl.online
          cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
          cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
          container-healthcheck-delay: 10

    - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v1.0.5
      inputs:
          vm-hostname: infrastructure.vm.xbhl.intranet
          vm-ssh-username: $SSH_USER
          vm-ssh-private-key: $SSH_PRIVATE_KEY
          service-name: traefik:infrastructure-vm
          container-name: traefik
          container-location: /opt/containers/traefik
          cloudflare-dns-entry-name: traefik-infrastructure.intranet.xbhl.online
          cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
          cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
          container-healthcheck-delay: 10

setup:generate-build-artifacts:
    script:
        - touch $BUILD_ARTIFACTS_DIR/.env
        - echo CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID >> $BUILD_ARTIFACTS_DIR/.env
        - echo CLOUDFLARE_ZONE_API_TOKEN=$CLOUDFLARE_ZONE_API_TOKEN >> $BUILD_ARTIFACTS_DIR/.env
        - echo CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_DNS_API_TOKEN >> $BUILD_ARTIFACTS_DIR/.env
