include:
    - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v1.0.3
      inputs:
          vm-hostname: media.vm.xbhl.intranet
          vm-ssh-username: $SSH_USER
          vm-ssh-private-key: $SSH_PRIVATE_KEY
          service-name: traefik:media-vm
          container-name: traefik
          container-location: /opt/containers/traefik
          cloudflare-dns-entry-name: traefik-media.intranet.xbhl.online
          cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
          cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
          container-healthcheck-delay: 10

    - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v1.0.3
      inputs:
          vm-hostname: infrastructure.vm.xbhl.intranet
          vm-ssh-username: $SSH_USER
          vm-ssh-private-key: $SSH_PRIVATE_KEY
          service-name: traefik:infrastructure-vm
          container-name: traefik
          container-location: /opt/containers/traefik
          cloudflare-dns-entry-name: traefik-infrastructure.intranet.xbhl.online
          cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
          cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
          container-healthcheck-delay: 10

load_cloudflare_dns_entry:
    stage: .pre
    script:
        - touch src/.env
        - echo CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID >> src/.env
        - echo CLOUDFLARE_ZONE_API_TOKEN=$CLOUDFLARE_ZONE_API_TOKEN >> src/.env
        - echo CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_DNS_API_TOKEN >> src/.env
    artifacts:
        paths:
            - src/.env
