entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true
                    priority: 10000
    websecure:
        address: ":443"
        transport:
            respondingTimeouts:
                readTimeout: 3600
        http:
            tls:
                certResolver: letsencrypt_prod
                domains:
                    - main: "xbhl.online"
                      sans:
                          - "*.xbhl.online"
                          - "*.intranet.xbhl.online"
                          - "*.nas.intranet.xbhl.online"
                          - "*.ha.intranet.xbhl.online"
    mqtt:
        address: ":1883"
    mqtts:
        address: ":8883"
    mqtt-webockets:
        address: ":9002"

serversTransport:
    insecureSkipVerify: false

certificatesResolvers:
    letsencrypt_stg:
        acme:
            email: barczynski.lukasz@gmail.com
            storage: /letsencrypt/acme-stg.json
            caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
            dnsChallenge:
                provider: cloudflare
                resolvers:
                    - 1.1.1.1:53
                    - 8.8.8.8:53

    letsencrypt_prod:
        acme:
            email: barczynski.lukasz@gmail.com
            storage: /letsencrypt/acme.json
            dnsChallenge:
                provider: cloudflare
                resolvers:
                    - 1.1.1.1:53
                    - 8.8.8.8:53

providers:
    file:
        directory: /dynamic-config-files
        watch: true
    docker: {}

api:
    dashboard: true
    insecure: false

ping: {}

log:
    level: WARN
