services:
    traefik:
        image: traefik:${TRAEFIK_VERSION:?err}
        container_name: traefik
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/ssl/certs:/etc/ssl/certs:ro
            - letsencrypt:/letsencrypt
            - static-config:/etc/traefik:ro
            - dynamic-config:/dynamic-config-files:ro
        environment:
            - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN:?err}
            - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN:?err}
        healthcheck:
            test: wget --quiet --tries=1 --spider http://localhost:8080/ping || exit 1
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s
        restart: unless-stopped

volumes:
    letsencrypt:
        driver: local

    static-config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./static-config

    dynamic-config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./dynamic-config
